import React, { createContext, useContext, useState } from 'react';

const translations = {
  tr: {
    // Menu & Layout
    brandTitle: 'DEPO & STOK MANAGEMENT',
    moduleCode: 'Modül Kodu: YM-02',
    liveEnv: 'Canlı Ortam',
    appHeaderTitle: 'Depo & Stok ERP Portalı',
    stockStatus: 'Stok Durumu',
    newTransaction: 'Stok Hareketi',
    kartoteks: 'Hareket Defteri (Kartoteks)',
    transactionsList: 'Hareket Listesi',
    materials: 'Malzeme Kartları',
    materialDefinitions: 'Malzeme Tanımları',
    warehouses: 'Depo Tanımları',
    reports: 'Raporlar ve Dışa Aktar',
    logout: 'Çıkış Yap',
    changePassword: 'Şifre Değiştir',

    // Menu Categories
    menuGroupStock: 'STOK & MALZEME',
    menuGroupTransactions: 'FİŞLER & HAREKETLER',
    menuGroupAnalysis: 'ANALİZ & RAPOR',
    menuGroupUser: 'KULLANICI & HESABIM',
    myProfile: 'Profilim',

    // Notifications Popover
    criticalPopoverTitle: 'Kritik Stok Uyarısı Alınan Ürünler',
    noCriticalAlerts: 'Şu an kritik seviyenin altında ürün bulunmamaktadır.',
    viewAllCriticalBtn: 'Tüm Kritik Ürünleri Stok Durumunda Gör →',
    liveCriticalTooltip: 'Canlı Kritik Stok Bildirimleri',
    
    // Auth & Pass
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre',
    updatePassword: 'Şifreyi Güncelle',
    cancel: 'Vazgeç',
    save: 'Kaydet',
    confirm: 'Onayla',
    loginTitle: 'DEPO & STOK ERP',
    loginSubTitle: 'Güvenli Giriş Portalı',
    secureLoginPortal: 'Güvenli Giriş Portalı',
    username: 'Kullanıcı Adı',
    password: 'Parola',
    showPassword: 'Şifreyi Göster',
    hidePassword: 'Şifreyi Gizle',
    rememberMe: 'Beni Hatırla',
    forgotPass: 'Şifremi Unuttum?',
    loginBtn: 'Sisteme Giriş Yap',
    loggingIn: 'Giriş Yapılıyor...',
    demoAccounts: 'HIZLI DEMO GİRİŞ HESAPLARI',
    forgotTitle: 'Şifre Sıfırlama Talebi',
    forgotInfo: 'Kullanıcı adınızı girerek sistem yöneticisine şifre sıfırlama talebi gönderebilirsiniz:',
    sendRequest: 'Talebi Gönder',
    close: 'Kapat',

    // Roles
    roleAdmin: 'Admin (Yönetici)',
    roleSorumlu: 'Depo Sorumlusu',
    rolePersonel: 'Depo Personeli',
    roleGoruntuleyici: 'Görüntüleyici',

    // Dashboard Executive
    dashWelcomeTitle: 'Stok & Depo Yönetim Paneli',
    dashSubtitle: 'Canlı depo envanter takibi, hareket analizleri ve kritik stok uyarı kontrolü.',
    quickNewInbound: 'Yeni Giriş Fişi',
    quickTransfer: 'Transfer Yap',
    quickReports: 'Analiz Raporları',
    totalStockValue: 'TOPLAM STOK DEĞERİ',
    activeDepotAndBalance: 'AKTİF DEPO & BAKİYE',
    depotUnit: 'Depo',
    warehouseDistTitle: 'Depo Bazlı Stok Dağılımı',
    categoryDistTitle: 'Kategoriye Göre Stok Oranı',
    recentMovementsTitle: 'Son Stok Hareketleri',
    seeAll: 'Tümünü Gör →',
    searchPanelTitle: 'Stok Durumu Arama & Süzgeç Paneli',
    tabStockListSearch: 'Stok Listesi & Live Arama',
    tabRegionalChartsMovements: 'Bölgesel Grafikler & Son Hareketler',
    depotLocationFilterLabel: 'DEPO LOKASYON FİLTRESİ (ÖNCE BÖLGE, SONRA DEPO SEÇİNİZ):',
    allWarehousesAndRegions: 'Tüm Depolar & Bölgeler',
    regionInDepots: 'İçindeki Depolar:',
    filteredSuffix: '(FİLTRELENEN)',
    filterBySuffix: '(FİLTREYE GÖRE)',
    clickToFilterSuffix: '(TIKLA SÜZ)',

    // Stock & Filters
    totalItems: 'TOPLAM KALEM SAYISI',
    criticalWarning: 'KRİTİK SEVİYE UYARISI',
    totalBalance: 'TOPLAM FİZİKSEL BAKİYE',
    selectWarehouse: 'Depo Lokasyonu Seçiniz',
    selectWarehousePlaceholder: 'Depo adı yazarak arayın...',
    selectGroup: 'Malzeme Kategorisi Seçiniz',
    selectGroupPlaceholder: 'Sayaç, Vana, Boru...',
    searchMaterial: 'Malzeme Kodu veya Adı Ara',
    searchMaterialPlaceholder: 'Örn: Van, Say, PE...',
    onlyCritical: 'Sadece Kritik Stoklar',
    exportExcel: "Excel'e Aktar",
    itemsUnit: 'Kalem',
    pcsUnit: 'Adet',
    noRecords: 'Kayıt bulunamadı.',
    
    // Table Headers
    materialCode: 'Malzeme Kodu',
    materialName: 'Malzeme Adı',
    category: 'Malzeme Kategorisi',
    warehouse: 'Depo Lokasyonu',
    shelf: 'Raf No',
    cell: 'Hücre No',
    materialStatus: 'Malzeme Durumu',
    currentBalance: 'Mevcut Bakiye',
    criticalLevel: 'Kritik Limit',
    status: 'Durum',
    actions: 'İşlemler',
    runningTotal: 'YÜRÜYEN BAKİYE',
    date: 'Tarih',
    receiptNo: 'Fiş No',
    createdUser: 'Oluşturan',
    completed: 'Tamamlandı',
    cancelled: 'İptal Edildi',
    
    // Movements Form & Receipt
    movementType: 'Hareket Tipi',
    inboundMovement: 'Giriş Hareketi',
    outboundMovement: 'Çıkış Hareketi (Satış/Kullanım)',
    transferMovement: 'Transfer Hareketi',
    sourceWarehouse: 'Kaynak Depo Seçiniz',
    targetWarehouse: 'Hedef Depo Seçiniz',
    description: 'Açıklama / Belge İrsaliye No',
    descPlaceholder: 'Evrak no veya açıklama giriniz...',
    movementItems: 'Stok Hareket Kalemleri',
    addRow: 'Satır Ekle',
    quantity: 'Miktar',
    unitPrice: 'Birim Fiyat',
    lineTotal: 'Toplam',
    grandTotal: 'GENEL TUTAR TOPLAMI:',
    createMovement: 'Stok Hareketi Oluştur',
    processing: 'İşleniyor...',
    available: 'Kullanılabilir',
    scrap: 'Hurda',
    scrapNotice: 'Hurda (Çıkış/Transfer Yapılamaz)',
    movementSuccess: 'Stok Hareketi Başarıyla Oluşturuldu!',
    createReceiptBtn: 'Fiş Oluştur (Görüntüle / Yazdır)',
    newMovementBtn: 'Yeni Stok Hareketi',
    goToListBtn: 'Hareket Listesine Git',
    officialReceiptTitle: 'RESMİ STOK HAREKET FİŞİ',
    printPdfBtn: 'Yazdır / PDF İndir',
    officialReceiptSub: 'RESMİ MUHASEBE STOK FİŞİ',
    deliveredBy: 'TESLİM EDEN',
    receivedBy: 'TESLİM ALAN',
    stampSignature: 'İmza / Kaşe',
    
    // Master Cards (Malzemeler & Depolar)
    addNewMaterial: 'Yeni Malzeme Ekle',
    addNewWarehouse: 'Yeni Depo Ekle',
    unit: 'Birim',
    active: 'Aktif',
    passive: 'Pasif',
    edit: 'Düzenle',
    locked: '(Kilitli)',
    cardStatus: 'Kart Aktiflik Durumu',
    warehouseStatus: 'Depo Aktiflik Durumu',
    activeWarehouse: 'Aktif Depo',
    passiveWarehouse: 'Pasif Depo',
    editMaterialTitle: 'Malzeme Kartı Düzenle',
    newMaterialTitle: 'Yeni Malzeme Ekipmanı',
    editWarehouseTitle: 'Depo Bilgisi Düzenle',
    newWarehouseTitle: 'Yeni Depo Ekle',
    warehouseCode: 'Depo Kodu',
    warehouseName: 'Depo Adı / Lokasyonu',
    responsiblePerson: 'Sorumlu Personel',

    // Reports Page i18n
    groupReportTitle: 'Malzeme Grubu Bazlı Stok Dağılımı',
    filteredCategoryLabel: 'Filtrelenen Kategori:',
    showAllCategories: 'Tüm Kategorileri Göster',
    groupTip: 'İpucu: Detaylarını incelemek ve kritik stoklarını süzmek istediğiniz kategoriye tıklayınız (Örn: Basınç Regülatörleri).',
    criticalReportTitle: 'Kritik Stok Uyarısı Alınan Ürünler',
    noCriticalInCategory: 'kategorisinde kritik stok uyarısı veren ürün bulunmamaktadır.',
    noCriticalFound: 'Kritik seviyede ürün bulunamadı.',
    itemCount: 'Kalem Sayısı',
    criticalCount: 'Kritik Sayı',
    purchaseAnalyticsTitle: '1 Yıllık Satın Alma & Fiyat Trend Analizi',
    totalPurchasedQty: 'Toplam Satın Alınan Miktar',
    totalSpendTRY: 'Toplam Harcama (₺ TL)',
    totalSpendUSD: 'Toplam Harcama ($ USD)',
    avgPriceInflation: 'Ortalama Birim Fiyat Değişimi',
    priceTrendChartTitle: 'Birim Fiyat Değişim Grafiği (₺ TL vs $ USD)',
    selectMaterialToAnalyze: 'Fiyat Trendini İncelemek İstediğiniz Malzemeyi Seçiniz',

    // Profile Page i18n
    profileTitle: 'Kişisel Profil Bilgileri',
    activeSession: 'Aktif Oturum',
    createdDateLabel: 'Kayıt:',
    fullNameLabel: 'Ad Soyad',
    emailAddressLabel: 'E-Posta Adresi',
    usernameFixedLabel: 'Kullanıcı adı sabittir.',
    systemRoleLabel: 'Sistem Rolü & Yetkisi',
    updateProfileBtn: 'Bilgilerimi Güncelle',
    quickNotesTitle: 'Hızlı Depo & Şahsi Notlarım',
    quickNotesSub: 'Depo operasyonları, mal kabulleri veya hatırlatmak istediğiniz şahsi notlarınızı buraya yazabilirsiniz. Notlarınız cihazınızda saklanır.',
    quickNotesPlaceholder: 'Örn: Yarın sabah Marmara Bölge Deposu\'ndan 50 adet PE boru çıkışı yapılacak. İrsaliye kontrol edilecek...',
    saveNoteBtn: 'Notu Kaydet',
    noteSavedBadge: 'Not Kaydedildi',
    passSecurityTitle: 'Parola & Güvenlik Ayarları',
    currentPassLabel: 'Mevcut Parola',
    newPassLabel: 'Yeni Parola',
    confirmNewPassLabel: 'Yeni Parola (Tekrar)',
    minSixCharsHelp: 'En az 6 karakter uzunluğunda olmalıdır.',
    changePassBtn: 'Parolayı Değiştir',
    sessionSecurityTitle: 'Oturum & Sistem Güvenliği',
    sessionTypeTitle: 'Oturum Türü & Süresi',
    sessionTypeDesc: 'JWT Token (60 Dakika Otomatik Yenileme)',
    dbEncryptTitle: 'Veritabanı Şifreleme',
    dbEncryptDesc: 'BCrypt Hashing Engine (Salted Pass)',
    authRegionsTitle: 'Yetkili Olduğu Bölge & Depolar',
    authRegionsDesc: 'Tüm Marmara, İç Anadolu & Akdeniz Depoları',
    activeLangCurrTitle: 'Aktif Dil & Para Birimi',
    
    // Pagination
    rowsPerPage: 'Sayfa Başına Satır:',
  },
  en: {
    // Menu & Layout
    brandTitle: 'STOCK & WAREHOUSE MANAGEMENT',
    moduleCode: 'Module Code: YM-02',
    liveEnv: 'Live Environment',
    appHeaderTitle: 'Stock & Warehouse ERP Portal',
    stockStatus: 'Stock Status',
    newTransaction: 'Stock Movement',
    kartoteks: 'Stock Movement Ledger',
    transactionsList: 'Movements History',
    materials: 'Material Master Cards',
    materialDefinitions: 'Material Definitions',
    warehouses: 'Warehouse Definitions',
    reports: 'Reports & Export',
    logout: 'Sign Out',
    changePassword: 'Change Password',

    // Menu Categories
    menuGroupStock: 'STOCK & MATERIALS',
    menuGroupTransactions: 'TRANSACTIONS',
    menuGroupAnalysis: 'ANALYSIS & REPORTS',
    menuGroupUser: 'USER & ACCOUNT',
    myProfile: 'My Profile',

    // Notifications Popover
    criticalPopoverTitle: 'Products with Critical Stock Warning',
    noCriticalAlerts: 'There are currently no items below critical stock level.',
    viewAllCriticalBtn: 'View All Critical Items in Stock Status →',
    liveCriticalTooltip: 'Live Critical Stock Notifications',
    
    // Auth & Pass
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    cancel: 'Cancel',
    save: 'Save',
    confirm: 'Confirm',
    loginTitle: 'WAREHOUSE & STOCK ERP',
    loginSubTitle: 'Secure Login Portal',
    secureLoginPortal: 'Secure Login Portal',
    username: 'Username',
    password: 'Password',
    showPassword: 'Show Password',
    hidePassword: 'Hide Password',
    rememberMe: 'Remember Me',
    forgotPass: 'Forgot Password?',
    loginBtn: 'Sign In to System',
    loggingIn: 'Signing In...',
    demoAccounts: 'QUICK DEMO ACCOUNTS',
    forgotTitle: 'Password Reset Request',
    forgotInfo: 'Enter your username to send a password reset request to the system administrator:',
    sendRequest: 'Send Request',
    close: 'Close',

    // Roles
    roleAdmin: 'Admin (Manager)',
    roleSorumlu: 'Warehouse Manager',
    rolePersonel: 'Warehouse Staff',
    roleGoruntuleyici: 'Viewer',

    // Dashboard Executive
    dashWelcomeTitle: 'Stock & Warehouse Management Panel',
    dashSubtitle: 'Live warehouse inventory tracking, movement analysis, and critical stock alert control.',
    quickNewInbound: 'New Inbound Receipt',
    quickTransfer: 'Transfer Stock',
    quickReports: 'Analysis Reports',
    totalStockValue: 'TOTAL STOCK VALUE',
    activeDepotAndBalance: 'ACTIVE WAREHOUSES & BALANCE',
    depotUnit: 'Warehouse',
    warehouseDistTitle: 'Stock Distribution by Warehouse',
    categoryDistTitle: 'Stock Ratio by Category',
    recentMovementsTitle: 'Recent Stock Movements',
    seeAll: 'View All →',
    searchPanelTitle: 'Stock Status Search & Filter Panel',
    tabStockListSearch: 'Stock List & Live Search',
    tabRegionalChartsMovements: 'Regional Charts & Recent Movements',
    depotLocationFilterLabel: 'WAREHOUSE LOCATION FILTER (SELECT REGION, THEN WAREHOUSE):',
    allWarehousesAndRegions: 'All Warehouses & Regions',
    regionInDepots: 'Warehouses inside:',
    filteredSuffix: '(FILTERED)',
    filterBySuffix: '(BY FILTER)',
    clickToFilterSuffix: '(CLICK TO FILTER)',

    // Stock & Filters
    totalItems: 'TOTAL ITEMS COUNT',
    criticalWarning: 'CRITICAL STOCK ALERT',
    totalBalance: 'TOTAL PHYSICAL BALANCE',
    selectWarehouse: 'Select Warehouse Location',
    selectWarehousePlaceholder: 'Search by warehouse name...',
    selectGroup: 'Select Material Category',
    selectGroupPlaceholder: 'Meters, Valves, Pipes...',
    searchMaterial: 'Search Material Code or Name',
    searchMaterialPlaceholder: 'e.g. Van, Say, PE...',
    onlyCritical: 'Only Critical Stocks',
    exportExcel: 'Export to Excel',
    itemsUnit: 'Items',
    pcsUnit: 'Pcs',
    noRecords: 'No records found.',
    
    // Table Headers
    materialCode: 'Material Code',
    materialName: 'Material Name',
    category: 'Material Category',
    warehouse: 'Warehouse Location',
    shelf: 'Shelf No',
    cell: 'Cell No',
    materialStatus: 'Material Status',
    currentBalance: 'Current Balance',
    criticalLevel: 'Critical Limit',
    status: 'Status',
    actions: 'Actions',
    runningTotal: 'RUNNING TOTAL',
    date: 'Date',
    receiptNo: 'Voucher No',
    createdUser: 'Created By',
    completed: 'Completed',
    cancelled: 'Cancelled',
    
    // Movements Form & Receipt
    movementType: 'Movement Type',
    inboundMovement: 'Inbound Movement',
    outboundMovement: 'Outbound Movement (Sale/Usage)',
    transferMovement: 'Transfer Movement',
    sourceWarehouse: 'Select Source Warehouse',
    targetWarehouse: 'Select Target Warehouse',
    description: 'Description / Invoice Document No',
    descPlaceholder: 'Enter document number or description...',
    movementItems: 'Stock Movement Line Items',
    addRow: 'Add Row',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    lineTotal: 'Total',
    grandTotal: 'GRAND TOTAL AMOUNT:',
    createMovement: 'Create Stock Movement',
    processing: 'Processing...',
    available: 'Available',
    scrap: 'Scrap',
    scrapNotice: 'Scrap (Issue/Transfer Prohibited)',
    movementSuccess: 'Stock Movement Created Successfully!',
    createReceiptBtn: 'Create Receipt (View / Print)',
    newMovementBtn: 'New Stock Movement',
    goToListBtn: 'Go to Movements History',
    officialReceiptTitle: 'OFFICIAL STOCK MOVEMENT VOUCHER',
    printPdfBtn: 'Print / Download PDF',
    officialReceiptSub: 'OFFICIAL ACCOUNTING STOCK VOUCHER',
    deliveredBy: 'DELIVERED BY',
    receivedBy: 'RECEIVED BY',
    stampSignature: 'Signature / Stamp',
    
    // Master Cards (Malzemeler & Depolar)
    addNewMaterial: 'Add New Material',
    addNewWarehouse: 'Add New Warehouse',
    unit: 'Unit',
    active: 'Active',
    passive: 'Passive',
    edit: 'Edit',
    locked: '(Locked)',
    cardStatus: 'Card Active Status',
    warehouseStatus: 'Warehouse Active Status',
    activeWarehouse: 'Active Warehouse',
    passiveWarehouse: 'Passive Warehouse',
    editMaterialTitle: 'Edit Material Master Card',
    newMaterialTitle: 'Add New Material Equipment',
    editWarehouseTitle: 'Edit Warehouse Info',
    newWarehouseTitle: 'Add New Warehouse',
    warehouseCode: 'Warehouse Code',
    warehouseName: 'Warehouse Name / Location',
    responsiblePerson: 'Responsible Staff',

    // Reports Page i18n
    groupReportTitle: 'Stock Distribution by Material Category',
    filteredCategoryLabel: 'Filtered Category:',
    showAllCategories: 'Show All Categories',
    groupTip: 'Tip: Click on any category row to inspect details and filter its critical stocks (e.g. Pressure Regulators).',
    criticalReportTitle: 'Products with Critical Stock Warning',
    noCriticalInCategory: 'category has no items with critical stock warnings.',
    noCriticalFound: 'No products found at critical level.',
    itemCount: 'Item Count',
    criticalCount: 'Critical Count',
    purchaseAnalyticsTitle: '1-Year Purchase & Price Trend Analysis',
    totalPurchasedQty: 'Total Purchased Quantity',
    totalSpendTRY: 'Total Spend (₺ TRY)',
    totalSpendUSD: 'Total Spend ($ USD)',
    avgPriceInflation: 'Avg. Unit Price Change',
    priceTrendChartTitle: 'Unit Price Trend Chart (₺ TRY vs $ USD)',
    selectMaterialToAnalyze: 'Select Material to Analyze Price Trend',

    // Profile Page i18n
    profileTitle: 'Personal Profile Information',
    activeSession: 'Active Session',
    createdDateLabel: 'Registered:',
    fullNameLabel: 'Full Name',
    emailAddressLabel: 'Email Address',
    usernameFixedLabel: 'Username is fixed.',
    systemRoleLabel: 'System Role & Permission',
    updateProfileBtn: 'Update My Information',
    quickNotesTitle: 'Quick Warehouse & Personal Notes',
    quickNotesSub: 'Write personal notes, warehouse operations or reminders here. Notes are stored locally on your device.',
    quickNotesPlaceholder: 'e.g. 50 PE pipes will be dispatched from Marmara Regional Warehouse tomorrow morning...',
    saveNoteBtn: 'Save Note',
    noteSavedBadge: 'Note Saved',
    passSecurityTitle: 'Password & Security Settings',
    currentPassLabel: 'Current Password',
    newPassLabel: 'New Password',
    confirmNewPassLabel: 'Confirm New Password',
    minSixCharsHelp: 'Must be at least 6 characters long.',
    changePassBtn: 'Change Password',
    sessionSecurityTitle: 'Session & System Security',
    sessionTypeTitle: 'Session Type & Duration',
    sessionTypeDesc: 'JWT Token (60 Minutes Auto Renewal)',
    dbEncryptTitle: 'Database Encryption',
    dbEncryptDesc: 'BCrypt Hashing Engine (Salted Pass)',
    authRegionsTitle: 'Authorized Regions & Warehouses',
    authRegionsDesc: 'All Marmara, Central Anatolia & Mediterranean Warehouses',
    activeLangCurrTitle: 'Active Language & Currency',
    
    // Pagination
    rowsPerPage: 'Rows per page:',
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('tr');

  const t = (key) => {
    return translations[lang]?.[key] || translations['tr']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
